repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=768
      - id: check-ast
      - id: check-json
        exclude: .vscode/.*\.json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.5.0"
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.50.2
    hooks:
      - id: protolint
        args:
          - -fix
