[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.28.0"
prost = "0.13"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
