# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protocol/metadata.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class Info(betterproto.Message):
    message: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class Error(betterproto.Message):
    message: str = betterproto.string_field(1)
    stack: str = betterproto.string_field(2)
    type: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class Metadata(betterproto.Message):
    at: datetime = betterproto.message_field(1)
    info: "Info" = betterproto.message_field(10, group="of")
    error: "Error" = betterproto.message_field(11, group="of")


@dataclass(eq=False, repr=False)
class Records(betterproto.Message):
    run_id: str = betterproto.string_field(1)
    metadata: List["Metadata"] = betterproto.message_field(2)
