name: Create release request

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Prerelease type (empty == normal)"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release-request:
    uses: zifeo/workflows/.github/workflows/release-request.yml@main
    with:
      prerelease: ${{ github.event.inputs.prerelease }}
