name: Test and release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-release:
    uses: zifeo/workflows/.github/workflows/py-test-release.yml@main
    with:
      python-matrix: '["3.11", "3.12"]'
      poetry-version: "1.8.3"
      python-version: "3.12"
      compose: "dev/redis.compose.yaml"
      pytest-args: "-o log_cli=true -vv --full-trace"
      publish-pypi: true
    secrets:
      pypi-token: ${{ secrets.PYPI_TOKEN }}
